version: 0.0
os: linux
files:
  - source: /
    destination: /myapp
#permissions:
#  - object: /myapp/startApp.sh
#    mode: 777
hooks:
  ApplicationStop:
    - location: stopApp.sh
      timeout: 10
  ApplicationStart:
    - location: startApp.sh
      timeout: 10
  ValidateService:
    - location: validateApp.sh
      timeout: 10
